version: '3.9'

services:

  docker-react:
    container_name: docker-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './:/app'
    ports:
      - "8084:80"
      - "80:80"
      